import Header from "./_components/Header/Header"
import ThemeProvider from "./_context/theme-provider"
import "./_styles/_globals.scss"

export const metadata = {
  title: "Jonathan Kila | Web Developer",
  description: "Generated by Next.js",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div class="counter">
          <img
            src="https://www.free-website-hit-counter.com/c.php?d=9&id=142620&s=5"
            alt="Hit Counter"
          />
        </div>
        <ThemeProvider>
          <Header />
          <main className="main">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  )
}
